# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 07:06
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
