# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0003_auto_20160616_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
