# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0006_upcomingevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
