# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vblog', '0007_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event_date', models.DateField()),
                ('details', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UpcomingEvents',
        ),
    ]
